name: Playwright Tests
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: docker compose up -d
      - uses: ./.github/actions/build
      - run: docker run --name=scoreboard --network=host --detach --init --env=PORT=8009 --env-file=.env.ci bemuse-scoreboard
      - name: Install Playwright Browsers
        run: pnpm exec playwright install --with-deps
      - name: Run Playwright tests
        run: pnpm exec dotenv -e .env.ci playwright test
      - name: Dump server logs
        if: always()
        run: docker logs scoreboard
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
